language: objective-c
osx_image: xcode8
branches:
  only:
    - master
before_install:
    - pod install --project-directory=Tests
script:
    - xcodebuild -version
    - xcodebuild test -workspace Tests/YLMomentTests.xcworkspace -scheme 'iOSTests' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES
    - bash <(curl -s https://codecov.io/bash) -cF ios
    - xcodebuild test -workspace Tests/YLMomentTests.xcworkspace -scheme 'OSXTests' -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES
    - bash <(curl -s https://codecov.io/bash) -cF osx
