source 'https://github.com/CocoaPods/Specs.git'

def import_pods
  pod 'Expecta', '~> 0'
end

target 'iOSTests' do
  platform :ios, '8.0'
  import_pods
end

target 'OSXTests' do
    platform :osx, '10.8'
    import_pods
end
